import React,{useEffect,useRef,useState} from 'react';
import {View} from 'react-native';
import {useLocalSearchParams,useRouter,type Href} from 'expo-router';
import {actionLabel,canCancel,formatDate,modeFor,resolveObject,routeObjectId,stateLabel,textValue,type Conversation,type Message,type RecordEntity} from '@milo/contracts';
import {Badge,Body,Button,Card,Field,Heading,Screen,styles} from '../../../components/ui';
import {useMilo} from '../../../lib/state';
import {draftScopeKey} from '../../../lib/session-guard';
import {usePrivateResult} from '../../../lib/use-private-result';
import {reconcilePrivateResponse,type AuthorizedSnapshot} from '../../../lib/private-results';
const validKinds=new Set(['conversation','action','memory','connection','job','task','draft']);
export default function Detail(){const params=useLocalSearchParams<{kind:string;id:string}>();const kind=String(params.kind);const id=routeObjectId(params.id);const app=useMilo();const data=app.snapshot;const router=useRouter();
  const [remote,setRemote]=usePrivateResult<RecordEntity>(data);const [availableMessages,setMessages]=usePrivateResult<Message[]>(data);const messages=availableMessages??[];const [text,setText]=useState('');const [error,setError]=useState<string|null>(null);
  const [result,setResult]=usePrivateResult<unknown>(data);const [busy,setBusy]=useState(false);const [receipt,setReceipt]=usePrivateResult<RecordEntity>(data);const [confirmation,setConfirmation]=useState('');
  const [sourceAction,setSourceAction]=usePrivateResult<{kind:'QUOTE'|'REACTION'|'FORWARD';source:Message}>(data);
  const [sourceText,setSourceText]=useState('Thanks!');const [emoji,setEmoji]=useState('🙏');const [routeId,setRouteId]=useState('');
  const latestAuthorized=useRef<AuthorizedSnapshot|null>(data);
  const fromSnapshot=data&&id?(kind==='draft'?data.drafts.find(row=>row.id===id):resolveObject(data,kind,id)):null;
  const record=app.mode==='live'?remote:fromSnapshot;const conversation=kind==='conversation'?record as Conversation|null:data?.conversations.find(row=>row.id===record?.conversation_id)??null;
  const draftKey=data&&conversation?draftScopeKey(data.user.id,data.workspace.id,conversation.id,conversation.provider_chat_id):'';
  useEffect(()=>{setReceipt(null);setSourceAction(null);setText('');setResult(null);setConfirmation('');setRouteId('');},[id,kind]);
  useEffect(()=>{let active=true;setRemote(null);setError(null);setMessages([]);
    if(!id||!validKinds.has(kind))return;
    if(app.mode==='live')app.request<{object:RecordEntity}>(`/v1/ui/resolve?kind=${encodeURIComponent(kind)}&id=${encodeURIComponent(id)}`)
      .then(value=>{if(active)setRemote(value.object);}).catch(error=>{if(active){setRemote(null);setError(error.message);}});
    return()=>{active=false;};},[id,kind,app.mode,data?.generated_at]);
  useEffect(()=>{if(kind!=='conversation'||!id||!record)return;let active=true;setText(app.draftFor(draftKey));
    app.request<Message[]>(`/v1/conversations/${id}/messages?limit=50`).then(value=>{if(active)setMessages(value.map(row=>({...row,conversation_id:id})));})
      .catch(error=>{if(active){setMessages([]);setError(error.message);}});return()=>{active=false;};},[id,kind,record?.id,data?.generated_at,draftKey]);
  if(!data)return null;if(!id||!validKinds.has(kind)||!record)return <Screen title="Unavailable object"><Card><Heading>This object is unavailable</Heading><Body>{error??'It may be expired, revoked, outside your current scope, or absent from the synthetic fixture.'}</Body><Body>No action was executed by opening this link.</Body><Button label="Return to Inbox" onPress={()=>router.replace('/inbox')}/></Card></Screen>;
  const send=async(path:string,method='POST',body?:unknown)=>{if(method!=='GET'&&!app.online)throw new Error('Refresh current authorized state before changing this object.');setBusy(true);setError(null);try{const value=await app.request<RecordEntity>(path,{method,body,idempotencyKey:`native-detail-${Date.now()}-${Math.random().toString(36).slice(2)}`});const fresh=await app.refresh();if(!fresh)throw new Error('Current scope was not confirmed. Refresh to reconcile this operation.');latestAuthorized.current=fresh;const current=reconcilePrivateResponse(value??{completed:true},data,fresh);setResult(current??{acknowledged:true,private_response_cleared:true,notice:'Review the current authorized object.'},fresh);return current??{id:value?.id,private_response_cleared:true} as RecordEntity;}catch(error){setError(error instanceof Error?error.message:'Request unavailable');throw error;}finally{setBusy(false);}};
  const run=(callback:()=>Promise<unknown>)=>void callback().catch(error=>setError(error instanceof Error?error.message:'Request unavailable'));
  const sourceIds=(record.source_message_ids??record.evidence_message_ids??[]) as string[];
  const payload=(record.payload??{}) as Record<string,unknown>;
  return <Screen title={kind==='conversation'?conversation!.title:kind==='action'?actionLabel(textValue(record.kind)):kind==='memory'?'Memory evidence':kind==='connection'?'Connection detail':kind==='draft'?'Exact draft review':kind==='job'?'Durable schedule':'Owner reminder'} contextId={conversation?.id}>
    <Button label="Back" secondary onPress={()=>router.canGoBack()?router.back():router.replace('/')}/>
    {kind==='conversation'&&conversation&&<><Card><Heading>Message {conversation.title}</Heading><Body small>Account {data.connections.find(row=>row.id===conversation.connector_id)?.account_id??'Resolving account'} · exact recipient {conversation.provider_chat_id}</Body><Badge status={conversation.control_state}/><Body small>Saved mode {modeFor(conversation,data.grants)} · current revision {conversation.revision}. Ask Milo is a separate contextual control.</Body>
      {conversation.control_state==='HUMAN_TAKEOVER'&&<><Body>Observed phone takeover · Milo will not resume from an incoming message.</Body><Button secondary label="Review per-chat Resume" onPress={()=>router.push('/tools/pause' as Href)}/></>}
      <View style={styles.row}><Button secondary label="Voice & memory inspector" onPress={()=>router.push('/tools/people' as Href)}/><Button secondary label="Chat Rules" onPress={()=>router.push('/tools/rules' as Href)}/></View></Card>
      {!messages.length&&<Card><Body>No available messages in this currently permitted scope. History may be partial or absent.</Body></Card>}
      {messages.map(message=><View key={message.id} style={[styles.card,{alignSelf:message.direction==='outbound'?'flex-end':'stretch',maxWidth:'94%'}]}>
        <Body small>{message.author_kind==='assistant'?'Milo · assistant':message.author_kind==='human_owner'?'You · verified human':message.direction==='outbound'?'Owner output · authorship unresolved':'Other participant'} · {formatDate(message.provider_timestamp,data.workspace.timezone,true)}</Body>
        {message.reply_to&&<Body small>Native reply source {message.reply_to}</Body>}<Body>{message.text}</Body><Body small>{message.origin??'Unknown'} source · revision {message.revision}</Body>
        <View style={styles.row}><Button secondary label="Quote this source" disabled={message.origin!=='live'} onPress={()=>{setSourceAction({kind:'QUOTE',source:message});setSourceText('Thanks!');}}/>
          <Button secondary label="Review reaction to this source" disabled={message.origin!=='live'} onPress={()=>setSourceAction({kind:'REACTION',source:message})}/>
          <Button secondary label="Forward source with a route" disabled={message.origin!=='live'} onPress={()=>{setSourceAction({kind:'FORWARD',source:message});setRouteId('');}}/></View></View>)}
      {sourceAction&&<Card><Heading>{actionLabel(sourceAction.kind)} · exact source review</Heading><Body>{sourceAction.source.text}</Body><Body small>Source {sourceAction.source.id} · revision {sourceAction.source.revision} · {conversation.title}. An authentic native record, fresh live trigger and current bounded rule are required.</Body>
        {sourceAction.kind==='QUOTE'&&<><Field label="Exact quoted response · limited supported intent" value={sourceText} onChangeText={setSourceText} multiline/><Body small>Native source metadata is preserved. General owner-authored messages use the separate composer below.</Body></>}
        {sourceAction.kind==='REACTION'&&<><Body>Choose a reaction. Verified owner habits and suitable source semantics remain mandatory.</Body><View style={styles.row}>{['🙏','😊','✅'].map(value=><Button key={value} secondary label={`${emoji===value?'Selected ':''}${value}`} onPress={()=>setEmoji(value)}/>)}</View></>}
        {sourceAction.kind==='FORWARD'&&<><Heading>Exact destination audience</Heading>{data.routes.filter(row=>row.enabled&&row.source_conversation_id===conversation.id).map(route=>{const destination=data.conversations.find(row=>row.id===route.destination_conversation_id);return <Button key={route.id} secondary label={`${routeId===route.id?'Selected · ':''}${destination?.title??'Unavailable audience'} · ${destination?.kind??'Unknown'} · ${destination?.provider_chat_id??''}`} disabled={!destination} onPress={()=>setRouteId(route.id)}/>;})}<Body small>The native forward uses this immutable source and exact granted route. It is never replaced by copied text.</Body><Button secondary label="Review forwarding routes" onPress={()=>router.push('/tools/rules' as Href)}/></>}
        <Button label="Authorize this exact operation under the current rule" disabled={busy||!app.online||data.workspace.paused||(sourceAction.kind==='FORWARD'&&!routeId)||(sourceAction.kind==='QUOTE'&&!sourceText.trim())} onPress={()=>run(async()=>{const action=await send('/v1/actions','POST',{conversation_id:conversation.id,kind:sourceAction.kind,intent:sourceAction.kind==='FORWARD'?'forwarding':'acknowledgement',
          trigger_message_id:messages.filter(row=>row.direction==='inbound'&&row.origin==='live').at(-1)?.id,target_message_id:sourceAction.source.id,
          ...(sourceAction.kind==='QUOTE'?{text:sourceText}:{}),...(sourceAction.kind==='REACTION'?{emoji}:{}),...(sourceAction.kind==='FORWARD'?{route_id:routeId}:{}),
          evidence_message_ids:[sourceAction.source.id],expected_context_revision:conversation.revision,expected_control_epoch:conversation.control_epoch});setSourceAction(null);router.push(`/detail/action/${action.id}` as Href);})}/>
        <Button secondary label="Cancel source review" onPress={()=>setSourceAction(null)}/></Card>}
      {messages.length>=50&&<Button secondary label="Load older permitted messages" onPress={()=>run(async()=>{const before=messages[0].provider_timestamp;const older=await app.request<Message[]>(`/v1/conversations/${id}/messages?limit=50&before=${encodeURIComponent(before)}`);setMessages(Array.from(new Map([...older,...messages].map(row=>[row.id,row])).values()));})}/>}
      <Card><Heading>Message {conversation.title}</Heading><Field label={`Message ${conversation.title} · Enter inserts a newline`} value={text} onChangeText={value=>{setText(value);app.setDraft(draftKey,value);}} multiline/>
        <Body small>Local unsent text stays bound to this owner, workspace, chat and exact recipient. It is never silently sent after reconnect.</Body><Button label="Review my exact message" disabled={!text.trim()||busy||!app.online} onPress={()=>run(async()=>{const draft=await send(`/v1/conversations/${conversation.id}/owner-drafts`,'POST',{text,expected_revision:conversation.revision,expected_control_epoch:conversation.control_epoch});if(!draft.private_response_cleared)setReceipt(draft,latestAuthorized.current);})}/>
        <Button secondary label="Ask Milo about this chat" onPress={()=>router.push({pathname:'/assistant',params:{conversation_id:conversation.id}} as Href)}/></Card>
      {receipt&&<Card><Heading>Exact recipient review</Heading><Body>{textValue(receipt.text)}</Body><Body small>{conversation.title} · {conversation.provider_chat_id} · hash {textValue(receipt.content_hash)}</Body><Button label="Approve and send this exact message" disabled={busy||data.workspace.paused||!app.online} onPress={()=>run(async()=>{await app.request(`/v1/drafts/${receipt.id}/approve`,{method:'POST',body:{content_hash:receipt.content_hash}});const accepted=await send(`/v1/drafts/${receipt.id}/dispatch`);setReceipt(accepted.private_response_cleared?null:accepted,latestAuthorized.current);if(['accepted','delivered','read'].includes(textValue(accepted.status))){setText('');app.setDraft(draftKey,'');}})}/><Body small>Provider uncertainty is held; there is no blind resend.</Body></Card>}
    </>}
    {kind==='action'&&<><Card><Badge status={textValue(record.status)}/><Heading>{actionLabel(textValue(record.kind))}</Heading><Body>Exact recipient {textValue(record.recipient_id)}</Body><Body>{textValue(record.text,textValue(payload.text))}</Body>
      {Boolean(payload.emoji)&&<Body>Emoji {textValue(payload.emoji)}</Body>}<Body small>Source chat {textValue(record.conversation_id)} · destination chat {textValue(record.destination_conversation_id)}</Body><Body small>Payload hash {textValue(record.payload_hash)} · reason {textValue(record.reason_code,'No hold reason reported')}</Body>
      <Body small>Source target {textValue(record.target_message_id,'None')} · route {textValue(record.route_id,textValue(payload.route_id,'None'))}</Body><Button secondary label="Load current evidence" onPress={()=>run(()=>send(`/v1/actions/${id}/evidence`,'GET'))}/>
      {canCancel(textValue(record.status))&&<Button label="Cancel before submission" disabled={busy} onPress={()=>run(()=>send(`/v1/actions/${id}/cancel`))}/>}
      {record.status==='uncertain'&&<Body>Submission uncertain. Opening this receipt or reconnecting never retries it. Reconciliation needs provider evidence.</Body>}</Card></>}
    {kind==='memory'&&<><Card><Badge status={textValue(record.status)}/><Body>{textValue(record.text)}</Body><Body small>Version {String(record.version)} · scope {textValue(record.conversation_id)} · validity {record.expires_at?formatDate(record.expires_at,data.workspace.timezone):'No stored expiry'}</Body>
      <Heading>Source evidence</Heading>{sourceIds.map(source=><Body small key={source}>Source {source} · revision {String((record.source_revision as Record<string,number>??{})[source]??'unknown')}</Body>)}<Body small>Allowed use remains this selected conversation. Identity linking never grants cross-chat sharing.</Body>
      <Field label="Owner correction" value={text} onChangeText={setText} multiline/><Button label="Save corrected memory" disabled={!text.trim()||busy} onPress={()=>run(async()=>{const current=await app.request<{object:RecordEntity}>(`/v1/ui/resolve?kind=memory&id=${id}`);if(current.object.version!==record.version)throw new Error('Memory changed. Refresh before correcting.');return send(`/v1/memories/${id}`,'PATCH',{text,expected_version:record.version});})}/>
      <Field label="Type FORGET to forget this derived memory" value={confirmation} onChangeText={setConfirmation}/><Button label="Forget derived memory" disabled={confirmation!=='FORGET'||busy} onPress={()=>run(async()=>{await send(`/v1/memories/${id}`,'DELETE');router.back();})}/><Body small>Forgetting suppresses active retrieval and dependent work. Original source deletion is a separate Privacy action.</Body></Card></>}
    {kind==='connection'&&<Card><Heading>{textValue(record.account_id)}</Heading><Badge status={textValue(record.status)}/><Body>Provider {textValue(record.provider)} · fence {String(record.fence??'Unavailable')}</Body><Body small>Live health, phone continuity and history completeness are independent dimensions.</Body><Button label="Load actual capability evidence" onPress={()=>run(()=>send(`/v1/connectors/${id}/capabilities`,'GET'))}/><Body>{JSON.stringify(record.capabilities,null,2)}</Body><Button secondary label="Review linking recovery" onPress={()=>router.push('/tools/reconnect' as Href)}/><Button label="Disconnect and revoke this connector" disabled={busy} onPress={()=>run(()=>send(`/v1/connectors/${id}`,'DELETE'))}/></Card>}
    {kind==='task'&&<Card><Heading>{textValue(record.title)}</Heading><Badge status={textValue(record.status)}/><Body>{formatDate(record.due_at,data.workspace.timezone)}</Body><Body small>Owner reminder · no messaging provider or booking is implied.</Body><Field label="Correct reminder title" value={text} onChangeText={setText}/><Button label="Save reminder correction" disabled={!text.trim()||busy} onPress={()=>run(()=>send(`/v1/tasks/${id}`,'PATCH',{expected_version:record.version,title:text}))}/><Button secondary label="Mark owner reminder complete" disabled={busy} onPress={()=>run(()=>send(`/v1/tasks/${id}`,'PATCH',{expected_version:record.version,status:'completed'}))}/></Card>}
    {kind==='job'&&<Card><Heading>{textValue(record.purpose,'Scheduled operation')}</Heading><Badge status={textValue(record.status)}/><Body>Exact text: {textValue(record.content)}</Body><Body small>Audience {textValue(record.conversation_id)} · {formatDate(record.due_at,textValue(record.timezone,data.workspace.timezone))} · expiry {formatDate(record.expires_at,data.workspace.timezone)}</Body><Body small>Version {String(record.version)} · recurrence {textValue(record.recurrence)} · observed runs {String(record.runs_done??0)}</Body>
      {['hold','resume','cancel'].map(operation=><Button key={operation} label={`${operation[0].toUpperCase()+operation.slice(1)} this exact schedule`} secondary disabled={busy||['expired','cancelled','completed'].includes(textValue(record.status))} onPress={()=>run(()=>send(`/v1/jobs/${id}`,'PATCH',{expected_version:record.version,operation}))}/>)}</Card>}
    {kind==='draft'&&<Card><Badge status={textValue(record.status)}/><Body>{textValue(record.text)}</Body><Body small>Exact recipient {textValue(record.recipient_id)} · content hash {textValue(record.content_hash)}</Body><Field label="Edit this optional draft" value={text} onChangeText={setText} multiline/><Button secondary label="Save exact draft edit" disabled={!text.trim()||busy} onPress={()=>run(()=>send(`/v1/drafts/${id}`,'PATCH',{text}))}/><Button label="Approve and send exact displayed draft" disabled={busy||data.workspace.paused||!app.online} onPress={()=>run(async()=>{await app.request(`/v1/drafts/${id}/approve`,{method:'POST',body:{content_hash:record.content_hash}});return send(`/v1/drafts/${id}/dispatch`);})}/><Button secondary label="Discard draft" disabled={busy} onPress={()=>run(()=>send(`/v1/drafts/${id}/reject`))}/><Button secondary label="Schedule an allowed exact message" onPress={()=>router.push('/tools/schedule' as Href)}/></Card>}
    {error&&<Card><Heading>Needs attention</Heading><Body>{error}</Body><Body small>Refresh current evidence before trying an outward action again.</Body></Card>}
    {busy&&<Body>Processing the explicit request…</Body>}{result!==null&&<Card><Heading>Structured receipt</Heading><Body>{JSON.stringify(result,null,2)}</Body></Card>}
  </Screen>;
}
