"""bound draft context to memory expiry

Revision ID: 62a08d908c78
Revises: bdb23cd7706f
"""
from alembic import op
import sqlalchemy as sa


revision = '62a08d908c78'
down_revision = 'bdb23cd7706f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('context_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'context_expires_at')
    # ### end Alembic commands ###
