"""Native Google proof challenges and revocable device sessions

Revision ID: 776b8a3e1f52
Revises: 2c71848ffaec
"""
from alembic import op
import sqlalchemy as sa


revision = '776b8a3e1f52'
down_revision = '2c71848ffaec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('native_login_challenges',
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('code_challenge', sa.String(length=43), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce_hash')
    )
    op.create_index(op.f('ix_native_login_challenges_expires_at'), 'native_login_challenges', ['expires_at'], unique=False)
    op.create_table('native_sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_native_sessions_expires_at'), 'native_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_native_sessions_user_id'), 'native_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_native_sessions_user_id'), table_name='native_sessions')
    op.drop_index(op.f('ix_native_sessions_expires_at'), table_name='native_sessions')
    op.drop_table('native_sessions')
    op.drop_index(op.f('ix_native_login_challenges_expires_at'), table_name='native_login_challenges')
    op.drop_table('native_login_challenges')
    # ### end Alembic commands ###
