"""encrypted owner context and durable followup tasks

Revision ID: 95f566068880
Revises: 62a08d908c78
"""
from alembic import op
import sqlalchemy as sa
import json
from cryptography.fernet import Fernet
from assistant.config import Settings

revision = '95f566068880'
down_revision = '62a08d908c78'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('source_revision', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_conversation_id'), 'tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    cipher = Fernet(Settings().prepare().encryption_key.encode())
    for table_name, field in [("drafts", "missing_facts"), ("style_profiles", "owner_rules")]:
        legacy = field + "_legacy"
        op.alter_column(table_name, field, new_column_name=legacy)
        # NOT NULL from creation; the temporary default is removed on PostgreSQL.
        empty = cipher.encrypt(b"[]").decode()
        op.add_column(table_name, sa.Column(field, sa.Text(), nullable=False, server_default=empty))
        table = sa.table(table_name, sa.column("id", sa.String()), sa.column(legacy, sa.JSON()),
                         sa.column(field, sa.Text()))
        for row in op.get_bind().execute(sa.select(table.c.id, table.c[legacy])).mappings():
            encoded = cipher.encrypt(json.dumps(row[legacy] or []).encode()).decode()
            op.get_bind().execute(table.update().where(table.c.id == row["id"]).values({field: encoded}))
        op.drop_column(table_name, legacy)
        if op.get_bind().dialect.name == "postgresql":
            op.alter_column(table_name, field, server_default=None)
    # ### end Alembic commands ###

def downgrade():
    # Do not silently decrypt stored private context during rollback.
    raise RuntimeError("Encrypted-context migration requires a forward fix; destructive downgrade is disabled")
