"""initial tenant scoped assistant schema

Revision ID: bdb23cd7706f
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = 'bdb23cd7706f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_nonces',
    sa.Column('nonce_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce_hash')
    )
    op.create_table('users',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('pause_generation', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_table('connectors',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.String(length=120), nullable=False),
    sa.Column('owner_sender_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('fence', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'account_id', name='uq_connector_account')
    )
    op.create_index(op.f('ix_connectors_workspace_id'), 'connectors', ['workspace_id'], unique=False)
    op.create_table('outbox',
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('aggregate_id', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_workspace_id'), 'outbox', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('provider_chat_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('control_epoch', sa.Integer(), nullable=False),
    sa.Column('control_state', sa.String(length=30), nullable=False),
    sa.Column('recipient_opted_in', sa.Boolean(), nullable=False),
    sa.Column('recipient_opted_out', sa.Boolean(), nullable=False),
    sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_send_allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'provider_chat_id', name='uq_conversation_provider')
    )
    op.create_index(op.f('ix_conversations_connector_id'), 'conversations', ['connector_id'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('automations',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_intents', sa.JSON(), nullable=False),
    sa.Column('max_replies_per_hour', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quiet_start', sa.String(length=5), nullable=False),
    sa.Column('quiet_end', sa.String(length=5), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_automations_workspace_id'), 'automations', ['workspace_id'], unique=False)
    op.create_table('drafts',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_id', sa.String(length=160), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('evidence_message_ids', sa.JSON(), nullable=False),
    sa.Column('missing_facts', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('conversation_revision', sa.Integer(), nullable=False),
    sa.Column('control_epoch', sa.Integer(), nullable=False),
    sa.Column('permission_version', sa.Integer(), nullable=False),
    sa.Column('pause_generation', sa.Integer(), nullable=False),
    sa.Column('connector_fence', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_conversation_id'), 'drafts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_drafts_workspace_id'), 'drafts', ['workspace_id'], unique=False)
    op.create_table('imports',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_sender_label', sa.String(length=160), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('date_order', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'source_hash', name='uq_import_source')
    )
    op.create_index(op.f('ix_imports_workspace_id'), 'imports', ['workspace_id'], unique=False)
    op.create_table('memories',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('source_revision', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('suppression_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('profile_or_model_version', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_conversation_id'), 'memories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memories_workspace_id'), 'memories', ['workspace_id'], unique=False)
    op.create_table('messages',
    sa.Column('connector_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('provider_message_id', sa.String(length=180), nullable=False),
    sa.Column('sender_id', sa.String(length=160), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('author_kind', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reply_to', sa.String(length=180), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('excluded_from_learning', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'connector_id', 'conversation_id', 'provider_message_id', name='uq_message_key')
    )
    op.create_index(op.f('ix_messages_connector_id'), 'messages', ['connector_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_table('permissions',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('retain', sa.Boolean(), nullable=False),
    sa.Column('learn', sa.Boolean(), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('send', sa.Boolean(), nullable=False),
    sa.Column('share', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_permissions_workspace_id'), 'permissions', ['workspace_id'], unique=False)
    op.create_table('style_profiles',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('sufficiency', sa.String(length=30), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('evidence_message_ids', sa.JSON(), nullable=False),
    sa.Column('owner_rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_profiles_conversation_id'), 'style_profiles', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_style_profiles_workspace_id'), 'style_profiles', ['workspace_id'], unique=False)
    op.create_table('suppressions',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressions_conversation_id'), 'suppressions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_suppressions_workspace_id'), 'suppressions', ['workspace_id'], unique=False)
    op.create_table('message_events',
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_message_events_conversation_id'), 'message_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_events_workspace_id'), 'message_events', ['workspace_id'], unique=False)
    op.create_table('scheduled_intents',
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('original_expression', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('workflow_registered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'idempotency_key', name='uq_schedule_idempotency')
    )
    op.create_index(op.f('ix_scheduled_intents_conversation_id'), 'scheduled_intents', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_scheduled_intents_due_at'), 'scheduled_intents', ['due_at'], unique=False)
    op.create_index(op.f('ix_scheduled_intents_workspace_id'), 'scheduled_intents', ['workspace_id'], unique=False)
    op.create_table('send_attempts',
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('provider_message_id', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('connector_fence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', name='uq_send_draft')
    )
    op.create_index(op.f('ix_send_attempts_conversation_id'), 'send_attempts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_send_attempts_workspace_id'), 'send_attempts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_send_attempts_workspace_id'), table_name='send_attempts')
    op.drop_index(op.f('ix_send_attempts_conversation_id'), table_name='send_attempts')
    op.drop_table('send_attempts')
    op.drop_index(op.f('ix_scheduled_intents_workspace_id'), table_name='scheduled_intents')
    op.drop_index(op.f('ix_scheduled_intents_due_at'), table_name='scheduled_intents')
    op.drop_index(op.f('ix_scheduled_intents_conversation_id'), table_name='scheduled_intents')
    op.drop_table('scheduled_intents')
    op.drop_index(op.f('ix_message_events_workspace_id'), table_name='message_events')
    op.drop_index(op.f('ix_message_events_conversation_id'), table_name='message_events')
    op.drop_table('message_events')
    op.drop_index(op.f('ix_suppressions_workspace_id'), table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_conversation_id'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index(op.f('ix_style_profiles_workspace_id'), table_name='style_profiles')
    op.drop_index(op.f('ix_style_profiles_conversation_id'), table_name='style_profiles')
    op.drop_table('style_profiles')
    op.drop_index(op.f('ix_permissions_workspace_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memories_workspace_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_conversation_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_imports_workspace_id'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_drafts_workspace_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_conversation_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_automations_workspace_id'), table_name='automations')
    op.drop_table('automations')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_connector_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_outbox_workspace_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_connectors_workspace_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('login_nonces')
    # ### end Alembic commands ###
