import React,{useEffect,useState} from 'react';
import {Share,View} from 'react-native';
import {useLocalSearchParams,useRouter,type Href} from 'expo-router';
import {actionLabel,formatDate,modeFor,numberValue,textValue,type RecordEntity} from '@milo/contracts';
import {Badge,Body,Button,Card,Field,Heading,Screen,styles} from '../../components/ui';
import {useMilo} from '../../lib/state';
import {usePrivateResult} from '../../lib/use-private-result';
import {reconcilePrivateResponse} from '../../lib/private-results';
import {WhatsAppConnection} from '../../components/whatsapp-connection';

const titles:Record<string,string>={onboarding:'Owner setup',preferences:'Owner preferences',connections:'Connections',
  'connection-route':'Connection route',pairing:'Link WhatsApp',identity:'Connected identity',scope:'Selected scope',learning:'Initial learning',
  people:'People & voice',voice:'Writing voice',preview:'Unsent style preview',auto:'Selected Auto setup',rules:'Rules',
  'rule-editor':'Rule editor',simulation:'Rule simulation',pause:'Pause replies & actions','catch-up':'Catch me up',teach:'Teach Milo',
  reminder:'Owner reminder',schedule:'Schedule a message',activity:'Activity',privacy:'Privacy',settings:'Settings',devices:'Security & devices',
  usage:'Usage & quota',notifications:'Notifications & focus','system-access':'System access',reconnect:'Reconnect',group:'Group voice',future:'Planned integrations'};
export default function Tool(){const {tool:parameter}=useLocalSearchParams<{tool:string}>();const tool=String(parameter);const app=useMilo();const data=app.snapshot;const router=useRouter();
  const [chatId,setChatId]=useState(data?.conversations[0]?.id??'');const [destination,setDestination]=useState('');
  const [text,setText]=useState('');const [name,setName]=useState('My Milo');const [timezone,setTimezone]=useState(data?.workspace.timezone??'Asia/Kolkata');
  const [localDate,setLocalDate]=useState(new Date(Date.now()+86400000).toISOString().slice(0,16));const [expiry,setExpiry]=useState(new Date(Date.now()+7*86400000).toISOString());
  const [quietStart,setQuietStart]=useState('21:00');const [quietEnd,setQuietEnd]=useState('09:00');const [rate,setRate]=useState('6');
  const [permissions,setPermissions]=useState({read:true,retain:true,learn:false,draft:true,send:false,share:false});
  const [allowed,setAllowed]=useState(['SEND_TEXT']);const [recurrence,setRecurrence]=useState('none');
  const [result,setResult]=usePrivateResult<unknown>(data);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const [sessions,setSessions]=useState<RecordEntity[]>([]);const [rule,setRule]=useState('history');
  const [rawDays,setRawDays]=useState(String(data?.retention?.raw_days??30));const [derivedDays,setDerivedDays]=useState(String(data?.retention?.derived_days??90));
  const [auditDays,setAuditDays]=useState(String(data?.retention?.audit_days??90));const [actionsBudget,setActionsBudget]=useState(String(data?.budget?.max_actions_per_day??''));
  const [tokensBudget,setTokensBudget]=useState(String(data?.budget?.max_tokens_per_day??''));const [costBudget,setCostBudget]=useState(String(data?.budget?.max_cost_microusd_per_day??''));
  const [sourceDelete,setSourceDelete]=useState('');const [conversationKind,setConversationKind]=useState('contact');
  useEffect(()=>{if(tool==='devices'&&app.mode==='live')app.request<{sessions:RecordEntity[]}>('/v1/auth/sessions').then(value=>setSessions(value.sessions)).catch(error=>setError(error.message));},[tool,app.mode]);
  if(!data)return null;const chat=data.conversations.find(row=>row.id===chatId);const connection=data.connections.find(row=>row.id===chat?.connector_id);
  const grant=data.grants.find(row=>row.conversation_id===chatId);const profile=data.styles.find(row=>row.conversation_id===chatId);
  const request=async(path:string,method='POST',body?:unknown)=>{if(method!=='GET'&&!app.online)throw new Error('Refresh current authorized state before changing this setting or operation.');setBusy(true);setError(null);try {const value=await app.request(path,{method,body,idempotencyKey:`native-request-${Date.now()}-${Math.random().toString(36).slice(2)}`});
    const fresh=await app.refresh();if(!fresh)throw new Error('The operation response arrived, but current scope was not confirmed. Refresh before reviewing or retrying.');const current=reconcilePrivateResponse(value??{completed:true},data,fresh);setResult(current??{acknowledged:true,private_response_cleared:true,notice:'The authorized view changed. Open the current object to review its details.'},fresh);return value;}catch(error){setError(error instanceof Error?error.message:'Request unavailable');throw error;}finally{setBusy(false);}};
  const go=(value:string)=>router.push(`/tools/${value}` as Href);
  const pickChat=<Card><Heading>Exact conversation scope</Heading>{data.conversations.map(row=><Button key={row.id} label={`${row.title} · ${row.kind}`} secondary disabled={chatId===row.id} onPress={()=>{setChatId(row.id);setText('');setResult(null);}}/>)}{chat&&<Body small>{connection?.account_id??'Account unavailable'} · recipient {chat.provider_chat_id} · revision {chat.revision}</Body>}</Card>;
  const toggle=(value:string)=>setAllowed(previous=>previous.includes(value)?previous.filter(item=>item!==value):[...previous,value]);
  const safeRun=(callback:()=>Promise<unknown>)=>void callback().catch(error=>{setError(error instanceof Error?error.message:'Request unavailable');setBusy(false);});
  const ruleForm=<>{pickChat}<Card><Heading>One bounded Auto grant</Heading><Body>Account linking grants no sending. Configure this exact chat once; currently supported safe matching intents then run without repeated message approval.</Body>
    <Body small>Text replies are limited to supported grounded intents. Broad personalized Auto is not quality-validated.</Body>
    {([['SEND_TEXT','Text replies · limited intents'],['QUOTE','Quoted replies · authentic source'],['REACTION','Reactions · owner habits and safe semantics'],['FORWARD','Native forwards · precise route']] as const).map(([value,label])=><Button key={value} label={`${allowed.includes(value)?'✓ ':''}${label}`} secondary onPress={()=>toggle(value)}/>)}
    <Field label="Maximum outgoing actions per hour" value={rate} onChangeText={setRate} keyboardType="number-pad"/>
    <Field label="Quiet start · HH:MM" value={quietStart} onChangeText={setQuietStart}/><Field label="Quiet end · HH:MM" value={quietEnd} onChangeText={setQuietEnd}/>
    <Field label="Grant expiry · ISO datetime with offset" value={expiry} onChangeText={setExpiry}/>
    <Button label="Save exact Auto grant" disabled={!chat||!allowed.length||busy} onPress={()=>safeRun(()=>request('/v1/automation/grants','PUT',{conversation_id:chatId,enabled:true,mode:'AUTO',
      allowed_actions:allowed,allowed_intents:['acknowledgement','allowed_clarification'],reaction_palette:allowed.includes('REACTION')?['🙏','😊','✅']:[],
      forward_route_ids:allowed.includes('FORWARD')?data.routes.filter(row=>row.source_conversation_id===chatId&&row.enabled).map(row=>row.id):[],
      require_grounded_facts:true,max_outgoing_per_hour:Number(rate),max_trigger_age_seconds:300,quiet_start:quietStart,quiet_end:quietEnd,timezone,expires_at:expiry,
      ...(grant?{expected_version:grant.version}:{})}))}/>
    <Button secondary label="Test a no-send scenario" onPress={()=>go('simulation')}/></Card></>;
  return <Screen title={titles[tool]??'Unavailable route'} contextId={['voice','preview','group','rule-editor','auto','teach'].includes(tool)?chatId:undefined}>
    {tool==='onboarding'&&<><Card><Heading>Start with exact boundaries</Heading><Body>Identity → owner preferences → eligible account → selected read/retain/learn scope → available history → provisional voice → one bounded Auto setup.</Body></Card>
      {!data.workspace.id&&<Card><Field label="Workspace name" value={name} onChangeText={setName}/><Field label="IANA timezone" value={timezone} onChangeText={setTimezone}/><Button label="Create my workspace" disabled={busy} onPress={()=>safeRun(()=>request('/v1/workspaces','POST',{name,timezone}))}/></Card>}
      {['preferences','connections','connection-route','pairing','identity','scope','learning','people','preview','auto'].map(step=><Button key={step} label={titles[step]} secondary onPress={()=>go(step)}/>)}</>}
    {tool==='preferences'&&<Card><Heading>Owner preferences</Heading><Body>Workspace timezone: {data.workspace.timezone}. Forms use explicit dates plus an IANA timezone.</Body><Body>Interface language: English. Writing language and tone are scoped in People & voice.</Body><Button label="Notification & focus choices" onPress={()=>go('notifications')}/><Button secondary label="Review per-person voice" onPress={()=>go('people')}/><Body small>Timezone is chosen when a workspace is created; existing workspace timezone edits are not supported by the current API.</Body></Card>}
    {tool==='connections'&&<><WhatsAppConnection key={`${app.mode}:${data.user.id}:${data.workspace.id}`}/>{data.connections.map(row=><Card key={row.id}><Heading>{row.label??row.provider}</Heading><Badge status={row.status}/><Body>Account {row.account_id}</Body><Body small>Connectivity does not prove full history or sending eligibility.</Body><Button secondary label="Open identity and capabilities" onPress={()=>router.push(`/detail/connection/${row.id}` as Href)}/></Card>)}
      <Button label="Choose a supported connection route" onPress={()=>go('connection-route')}/><Button secondary label="Review reconnect recovery" onPress={()=>go('reconnect')}/></>}
    {tool==='connection-route'&&<><Card><Heading>Personal WhatsApp</Heading><Body>Same-number personal linking is unavailable until a tested eligible adapter is deployed. No QR or pairing code is fabricated.</Body><Button secondary label="Review linking requirements" onPress={()=>go('pairing')}/></Card>
      <Card><Heading>Text-history import</Heading><Body>Create an export-only account namespace and selected chat. Imported history can support preview and evidence; it sends nothing and creates no native originals.</Body><Field label="Account namespace" value={name} onChangeText={setName}/><Field label="Exact owner label in the export" value={text} onChangeText={setText}/>
      <Button label="Create export-only connection" disabled={!data.workspace.id||!text.trim()||busy} onPress={()=>safeRun(()=>request('/v1/connectors','POST',{workspace_id:data.workspace.id,provider:'export_only',account_id:name,owner_sender_id:text}))}/><Button secondary label="Choose chat scope" onPress={()=>go('scope')}/></Card>
      <WhatsAppConnection key={`${app.mode}:${data.user.id}:${data.workspace.id}`}/></>}
    {tool==='pairing'&&<Card><Heading>Linking unavailable</Heading><Body>Personal QR/code pairing is not implemented by the deployed connector. A QR on the same phone would need a verified app-switch code route or an explained second screen.</Body><Body small>No pairing material is cached, copied or placed in notifications.</Body><Button label="Back to connection routes" onPress={()=>go('connection-route')}/></Card>}
    {tool==='identity'&&<>{data.connections.map(row=><Card key={row.id}><Heading>{row.account_id}</Heading><Badge status={row.status}/><Body small>{row.provider==='mock'?'Synthetic identity; no real phone linked':'Account identity requires provider verification and actual health evidence.'}</Body><Button label="Open account detail" secondary onPress={()=>router.push(`/detail/connection/${row.id}` as Href)}/></Card>)}</>}
    {tool==='scope'&&<>{pickChat}<Card><Heading>Selected chat permissions</Heading>{Object.entries(permissions).map(([key,value])=><Button key={key} label={`${value?'✓ ':''}${key[0].toUpperCase()+key.slice(1)}`} secondary onPress={()=>setPermissions(previous=>({...previous,[key]:!value}))}/>)}
      <Body small>Learn, send and cross-audience share are separate. Group scope never inherits a direct-chat permission.</Body><Button label="Save exact chat permissions" disabled={!chat||busy} onPress={()=>safeRun(()=>request(`/v1/conversations/${chatId}/permissions`,'PUT',permissions))}/></Card>
      <Card><Heading>Add a selected conversation</Heading><Field label="Readable chat title" value={name} onChangeText={setName}/><Field label="Exact provider chat ID" value={text} onChangeText={setText}/>
      <View style={styles.row}>{['contact','group'].map(value=><Button key={value} secondary label={`${conversationKind===value?'Selected · ':''}${value==='group'?'Group':'Direct chat'}`} onPress={()=>setConversationKind(value)}/>)}</View>
      {data.connections.map(row=><Button key={row.id} secondary label={`${destination===row.id?'✓ ':''}${row.account_id}`} onPress={()=>setDestination(row.id)}/>)}
      <Button label="Create this exact conversation scope" disabled={!destination||!text.trim()||busy} onPress={()=>safeRun(async()=>{const row=await request('/v1/conversations','POST',{connector_id:destination,provider_chat_id:text,title:name,kind:conversationKind}) as RecordEntity;
        await request(`/v1/conversations/${row.id}/permissions`,'PUT',permissions);})}/></Card></>}
    {tool==='learning'&&<>{pickChat}<Card><Heading>Available history, honestly</Heading><Body>Counts refer to observed selected batches. Completion of one import is not lifetime completeness.</Body><Field label="Paste a WhatsApp text export" value={text} onChangeText={setText} multiline maxLength={200000}/><Field label="Exact owner label" value={name} onChangeText={setName}/>
      <Button label="Preview import · no sends" disabled={!chat||!text||busy} onPress={()=>safeRun(()=>request('/v1/imports/preview','POST',{conversation_id:chatId,text,owner_sender_label:name,date_order:'DMY',timezone}))}/>
      <Button label="Import selected history · no sends" disabled={!chat||!text||busy} secondary onPress={()=>safeRun(()=>request('/v1/imports','POST',{conversation_id:chatId,text,owner_sender_label:name,date_order:'DMY',timezone}))}/><Body small>DMY interpretation is explicit. Other export date orders can be configured from the web import form.</Body></Card></>}
    {(tool==='people'||tool==='voice'||tool==='preview'||tool==='group')&&<>{pickChat}<Card><Heading>{chat?.kind==='group'?'Independent group voice':'Person-specific voice'}</Heading><Body>{numberValue(profile?.sample_count)} observed eligible examples · {textValue(profile?.sufficiency,'No profile')}</Body><Body small>Sample counts guide preview, not quality certification. Human-owner examples, assistant echoes and reaction habits remain distinct.</Body>
      {chat?.kind==='group'&&<Body>Participants and membership freshness are unavailable in the current adapter. No private-DM memory is usable here without an exact sharing grant.</Body>}
      <Button label="Generate unsent style preview" disabled={!chat||busy} onPress={()=>safeRun(()=>request(`/v1/conversations/${chatId}/style-preview`))}/>
      <Field label="Scoped writing preference" value={text} onChangeText={setText} multiline/><Button secondary label="Save explicit voice preference" disabled={!chat||!text.trim()||busy} onPress={()=>safeRun(()=>request(`/v1/conversations/${chatId}/style-profile`,'PATCH',{owner_rules:[text],reviewed:true,expected_version:profile?.version??0}))}/></Card>
      <Card><Heading>Assistant-local contacts</Heading>{data.contacts.map(row=><View key={row.id}><Body>{textValue(row.display_name)}</Body><Body small>Saved destination: {textValue(row.saved_destination)} · provider identity {textValue(row.provider_identity)}</Body></View>)}
      <Field label="Owner-supplied contact display name" value={name} onChangeText={setName}/><Button label="Save verified peer locally" disabled={!chat||busy} onPress={()=>safeRun(async()=>{const messages=await app.request<RecordEntity[]>(`/v1/conversations/${chatId}/messages?limit=20`);
        const source=messages.find(row=>row.direction==='inbound');if(!source)throw new Error('No available verified peer source');return request('/v1/contacts','POST',{conversation_id:chatId,source_message_id:source.id,destination:'assistant_local',display_name:name});})}/>
      <Button secondary label="Allow local contact auto-save for this chat" disabled={!chat||busy} onPress={()=>safeRun(()=>request(`/v1/conversations/${chatId}/contact-save-grant`,'PUT',{enabled:true,expires_at:expiry}))}/><Body small>WhatsApp, Google and phone OS contact writes are unavailable. A local record is not a phone address-book write.</Body></Card></>}
    {tool==='rules'&&<><Button label="Create or edit a bounded rule" onPress={()=>go('rule-editor')}/>{data.grants.map(row=><Card key={row.id}><Heading>{data.conversations.find(chat=>chat.id===row.conversation_id)?.title??'Selected chat'}</Heading><Body>Configured Auto · {row.enabled?'Enabled':'Disabled'} · version {numberValue(row.version)}</Body><Body small>Expires {formatDate(row.expires_at,timezone)}. Current takeover, pause, capability and permission gates still apply.</Body><Button secondary label="Disable this grant" disabled={busy} onPress={()=>safeRun(()=>request(`/v1/automation/grants/${row.id}`,'DELETE'))}/></Card>)}
      <Card><Heading>Exact forwarding routes</Heading>{data.routes.map(row=><Body key={row.id}>{data.conversations.find(chat=>chat.id===row.source_conversation_id)?.title} → {data.conversations.find(chat=>chat.id===row.destination_conversation_id)?.title} · version {numberValue(row.version)}</Body>)}
      {pickChat}<Heading>Destination audience</Heading>{data.conversations.filter(row=>row.id!==chatId).map(row=><Button key={row.id} label={`${destination===row.id?'✓ ':''}${row.title} · ${row.kind}`} secondary onPress={()=>setDestination(row.id)}/>)}
      <Button label="Grant this precise forward route" disabled={!destination||!chat||busy} onPress={()=>safeRun(()=>request('/v1/forward-routes','POST',{source_conversation_id:chatId,destination_conversation_id:destination,
        categories:['owner_selected_text'],audience:data.conversations.find(row=>row.id===destination)?.kind??'contact',expires_at:expiry}))}/></Card></>}
    {(tool==='rule-editor'||tool==='auto')&&ruleForm}
    {tool==='simulation'&&<Card><Heading>No-send rule simulation</Heading><Body>This deterministic synthetic check submits no model or provider operation. Current server authority is rechecked for any real execution.</Body>{['history','phone takeover','unsupported capability','fresh acknowledgement'].map(value=><Button key={value} label={`${rule===value?'✓ ':''}${value}`} secondary onPress={()=>setRule(value)}/>)}
      <Button label="Run synthetic rule check" onPress={()=>setResult({simulation:true,outgoing:false,
        outcome:rule==='fresh acknowledgement'?'Candidate only; current grant and final dispatcher checks required':'Held',
        reason:rule==='history'?'HISTORY_ONLY':rule==='phone takeover'?'HUMAN_TAKEOVER':rule==='unsupported capability'?'CAPABILITY_UNAVAILABLE':'Bounded acknowledgement'})}/></Card>}
    {tool==='pause'&&<><Card><Heading>Global external actions</Heading><Badge status={data.workspace.paused?'Paused':'Active'}/><Body>{app.pausePending?'Requested—waiting for server confirmation':'Last acknowledged generation '+data.workspace.pause_generation}</Body>
      <Body>Durable external schedules are held. Owner reminders and separately granted local contact storage are independent.</Body><Button label={data.workspace.paused?'Request fresh Resume':'Pause replies & actions'} disabled={busy} onPress={()=>safeRun(()=>app.pause(!data.workspace.paused))}/></Card>
      {pickChat}<Card><Heading>Only this conversation</Heading><Body>{chat?.title} · {chat?.control_state}. Phone takeover remains sticky until explicit per-chat Resume.</Body><Button secondary label="Handle this chat myself" disabled={!chat||busy} onPress={()=>safeRun(()=>request(`/v1/conversations/${chatId}/takeover`))}/><Button label="Resume this exact chat" disabled={!chat||busy} onPress={()=>safeRun(()=>request(`/v1/conversations/${chatId}/resume`))}/></Card></>}
    {tool==='catch-up'&&<><Card><Heading>Your permitted catch-up</Heading><Body>Source-linked previews and precise receipts. No message is marked handled just because you read it.</Body><Button label="Refresh current catch-up" disabled={busy} onPress={()=>safeRun(()=>request(`/v1/assistant/digest?workspace_id=${data.workspace.id}`,'GET'))}/></Card>{data.conversations.slice(0,20).map(row=><Card key={row.id}><Heading>{row.title}</Heading><Body>{row.preview??'Open the conversation for available source context.'}</Body><Body small>Saved {modeFor(row,data.grants)} · {row.control_state}</Body><Button secondary label="Open scoped conversation" onPress={()=>router.push(`/detail/conversation/${row.id}` as Href)}/></Card>)}</>}
    {tool==='teach'&&<>{pickChat}<Card><Heading>An explicit, scoped preference</Heading><Field label="What should Milo remember for this chat?" value={text} onChangeText={setText} multiline/><Button label="Create owner-confirmed memory" disabled={!text.trim()||!chat||busy} onPress={()=>safeRun(async()=>{const messages=await app.request<RecordEntity[]>(`/v1/conversations/${chatId}/messages?limit=20&derived_evidence=true`);
      if(!messages.length)throw new Error('Memory needs available evidence in this exact chat');return request('/v1/assistant/commands','POST',{command:'teach_me',workspace_id:data.workspace.id,conversation_id:chatId,text,status:'confirmed',source_message_ids:[messages[messages.length-1].id]});})}/><Body small>Creating a memory grants no send or sharing permission.</Body></Card></>}
    {(tool==='reminder'||tool==='schedule')&&<>{tool==='schedule'&&pickChat}<Card><Heading>{tool==='reminder'?'A private owner reminder':'An exact durable external message'}</Heading><Field label={tool==='reminder'?'Reminder title':'Exact recipient message'} value={text} onChangeText={setText} multiline/>
      <Field label="Local date/time · YYYY-MM-DDTHH:MM" value={localDate} onChangeText={setLocalDate}/><Field label="IANA timezone" value={timezone} onChangeText={setTimezone}/>
      {tool==='schedule'&&<><Field label="Execution expiry · ISO with offset" value={expiry} onChangeText={setExpiry}/><View style={styles.row}>{['none','daily','weekly'].map(value=><Button key={value} secondary label={`${recurrence===value?'✓ ':''}${value}`} onPress={()=>setRecurrence(value)}/>)}</View><Body small>Recurrence preserves local wall-clock time. Ambiguous or nonexistent DST times are rejected for review.</Body></>}
      <Button label={tool==='reminder'?'Save owner reminder':'Authorize exact external schedule'} disabled={!text.trim()||busy||(tool==='schedule'&&!chat)} onPress={()=>safeRun(async()=>{const resolved=await app.request<{due_at:string}>('/v1/schedules/resolve-time',{method:'POST',body:{local_datetime:localDate,timezone,ambiguity_policy:'reject',gap_policy:'reject'}});
        if(tool==='reminder')return request('/v1/tasks','POST',{workspace_id:data.workspace.id,title:text,due_at:resolved.due_at,timezone});
        return request('/v1/jobs','POST',{workspace_id:data.workspace.id,conversation_id:chatId,idempotency_key:`native-job-${Date.now()}`,purpose:'Owner-authorized exact scheduled message',action_kind:'SEND_TEXT',content:text,
          evidence_message_ids:[],memory_ids:[],due_at:resolved.due_at,expires_at:expiry,timezone,recurrence,max_runs:recurrence==='none'?1:7,max_runs_per_hour:3,max_lateness_seconds:3600,ambiguity_policy:'reject',gap_policy:'reject'});
      })}/></Card></>}
    {tool==='activity'&&<><Field label="Filter activity" value={text} onChangeText={setText}/>{data.activity.filter(row=>JSON.stringify(row).toLowerCase().includes(text.toLowerCase())).map(row=><Card key={row.id}><Heading>{textValue(row.action)}</Heading><Body small>{formatDate(row.created_at,timezone)} · source {textValue(row.resource_id)}</Body><Button secondary label="Resolve permitted source" onPress={()=>router.push(`/detail/action/${textValue(row.resource_id)}` as Href)}/></Card>)}</>}
    {tool==='privacy'&&<>{pickChat}<Card><Heading>Delete source chat data</Heading><Body>{chat?.title??'Choose an exact selected chat'} · this is separate from forgetting one derived memory.</Body><Field label="Type DELETE CHAT to remove stored source data" value={sourceDelete} onChangeText={setSourceDelete}/><Button label="Delete this exact chat's stored data" disabled={!chat||sourceDelete!=='DELETE CHAT'||busy} onPress={()=>safeRun(async()=>{await request(`/v1/conversations/${chatId}/data`,'DELETE');setSourceDelete('');setText('');})}/></Card><Card><Heading>Retention</Heading><Field label="Raw record retention · days" value={rawDays} onChangeText={setRawDays} keyboardType="number-pad"/><Field label="Derived memory/profile retention · days" value={derivedDays} onChangeText={setDerivedDays} keyboardType="number-pad"/><Field label="Audit metadata retention · days" value={auditDays} onChangeText={setAuditDays} keyboardType="number-pad"/>
      <Button label="Save retention policy" disabled={busy} onPress={()=>safeRun(()=>request('/v1/privacy/retention','PUT',{workspace_id:data.workspace.id,expected_version:data.retention?.version??0,raw_days:Number(rawDays),derived_days:Number(derivedDays),audit_days:Number(auditDays)}))}/><Body small>Provider records and backup expiry require separate verified lifecycle evidence. Privacy tombstones prevent replay restoration.</Body></Card>
      <Card><Heading>Your data</Heading><Button secondary label="Export my authorized scope" disabled={busy} onPress={()=>safeRun(async()=>{const exported=await app.request(`/v1/data-export?workspace_id=${data.workspace.id}`,{method:'POST'});await Share.share({title:'Milo owner export',message:JSON.stringify(exported,null,2)});setResult({exported:true,destination:'Owner-triggered system share'});})}/>
      <Body>Forget a derived memory from its detail. Delete source chat data separately. Account deletion immediately blocks active retrieval; external provider lifecycle is separate.</Body><Field label="Type DELETE to delete this workspace account data" value={text} onChangeText={setText}/><Button label="Delete this workspace data" disabled={text!=='DELETE'||busy} onPress={()=>safeRun(async()=>{await request(`/v1/account-data?workspace_id=${data.workspace.id}`,'DELETE');await app.logout();router.replace('/sign-in');})}/></Card></>}
    {tool==='usage'&&<><Card><Heading>Actual recorded units</Heading><Body>{JSON.stringify(data.budget?.usage??{})}</Body><Body small>UTC admission window. Conservative model reservations and uncertainty remain counted; no invented time-saved metric.</Body></Card><Card><Field label="Maximum external actions/day · blank unlimited" value={actionsBudget} onChangeText={setActionsBudget} keyboardType="number-pad"/><Field label="Maximum tokens/day · blank unlimited" value={tokensBudget} onChangeText={setTokensBudget} keyboardType="number-pad"/><Field label="Maximum cost/day · micro-USD, blank unlimited" value={costBudget} onChangeText={setCostBudget} keyboardType="number-pad"/><Button label="Save hard workspace ceilings" disabled={busy} onPress={()=>safeRun(()=>request(`/v1/workspaces/${data.workspace.id}/budget`,'PUT',{expected_version:data.budget?.version??0,max_actions_per_day:actionsBudget===''?null:Number(actionsBudget),max_tokens_per_day:tokensBudget===''?null:Number(tokensBudget),max_cost_microusd_per_day:costBudget===''?null:Number(costBudget)}))}/><Body small>A real model cost ceiling fails closed until exact-model pricing is configured and attested by the operator.</Body></Card></>}
    {tool==='devices'&&<><Card><Heading>Protected application sessions</Heading><Body>Bearer access and rotating refresh material are stored only in SecureStore, bound to this build environment and API origin. No WhatsApp keys or chat archives are stored there.</Body><Button label="Sign out and clear local private state" onPress={()=>safeRun(async()=>{await app.logout();router.replace('/sign-in');})}/></Card>
      {app.mode==='demo'?<Body>Synthetic session · no registered device or push token.</Body>:sessions.map(row=><Card key={row.id}><Heading>{textValue(row.device_name,'Application session')}</Heading><Body>{textValue(row.kind)} · {textValue(row.platform)} · expires {formatDate(row.expires_at,timezone)}</Body><Button secondary label="Revoke this app session" onPress={()=>safeRun(()=>request(`/v1/auth/sessions/${row.id}`,'DELETE'))}/></Card>)}</>}
    {(tool==='notifications'||tool==='system-access')&&<><Card><Heading>System permissions</Heading><Body>Microphone: not requested · transcription adapter unavailable.</Body><Body>Notifications: not requested · APNs/FCM and device registration unavailable.</Body><Body>Phone contacts: not requested · device-targeted contact executor unavailable.</Body><Body small>No OS prompt is triggered for an unavailable adapter. Denying any future optional permission will preserve text-first core use.</Body><Button label="Talk · unavailable" disabled onPress={()=>{}}/><Button label="Enable push · unavailable" disabled onPress={()=>{}}/><Button label="Phone contact sync · unavailable" disabled onPress={()=>{}}/></Card>
      <Card><Heading>Focus & privacy</Heading><Body>Auto quiet hours live in the exact rule, separate from notification preferences. No private lock-screen body or automatic read-aloud is enabled.</Body><Button secondary label="Review quiet hours" onPress={()=>go('rule-editor')}/></Card></>}
    {tool==='settings'&&<>{['preferences','notifications','devices','privacy','usage','system-access','future'].map(value=><Button key={value} label={titles[value]} secondary onPress={()=>go(value)}/>)}</>}
    {tool==='reconnect'&&<Card><Heading>Observe before resuming</Heading><Body>App internet state, WhatsApp connection health, history coverage and last acknowledged policy are separate. Foreground refresh reconciles current server state; an old send tap is never replayed.</Body><Button label="Fetch current authorized snapshot" onPress={()=>safeRun(()=>app.refresh())}/><Button secondary label="Review connection health" onPress={()=>go('connections')}/></Card>}
    {tool==='future'&&<Card><Heading>Planned, not connected</Heading>{['Gmail','Calendar','Other social channels','Meetings & teams'].map(value=><Body key={value}>{value} · planned · separate eligible API, permission and roles required.</Body>)}</Card>}
    {!titles[tool]&&<Card><Heading>Unavailable destination</Heading><Body>This route resolves no permitted product object and initiates no action.</Body><Button label="Return Home" onPress={()=>router.replace('/')}/></Card>}
    {busy&&<Body>Processing the explicit request…</Body>}{error&&<Card><Heading>Needs attention</Heading><Body>{error}</Body><Body small>The request is not silently retried. Review current state before any outward action.</Body></Card>}
    {result!==null&&<Card><Heading>Structured outcome</Heading><Body>{JSON.stringify(result,null,2)}</Body></Card>}
  </Screen>;
}
